package com.cropcast.app.ui.localization

import androidx.compose.runtime.Composable
import androidx.compose.runtime.staticCompositionLocalOf

val LocalCropCastLanguage = staticCompositionLocalOf { "English" }

private val hiligaynon = mapOf(
    "Home" to "Balay",
    "Welcome" to "Maayong pag-abot",
    "Monthly data readiness" to "Kahandaan sang binulan nga datos",
    "Important notices" to "Importante nga mga pahibalo",
    "Test data is simulated and is not field evidence" to "Ang test nga datos gin-simulate kag indi ebidensya halin sa aktuwal nga latagon",
    "View full recommendation" to "Tan-awa ang bug-os nga rekomendasyon",
    "of" to "sa",
    "required readings collected" to "kinahanglan nga mga pagbasa ang natipon",
    "Ready for recommendation" to "Handa na para sa rekomendasyon",
    "More readings needed" to "Kinahanglan pa sang dugang nga mga pagbasa",
    "No active alerts" to "Wala sang aktibo nga alerto",
    "Sensor is offline; using the latest available data" to "Offline ang sensor; ginagamit ang pinakabag-o nga datos nga ara",
    "Recommendation" to "Rekomendasyon",
    "Sensor details" to "Detalye sang sensor",
    "Crop Recommendation" to "Rekomendasyon sang Tanom",
    "Next month recommendation" to "Rekomendasyon para sa masunod nga bulan",
    "Forecast for" to "Tagna para sa",
    "past months used" to "nagligad nga mga bulan ang gin-gamit",
    "Based on historical sensor data" to "Base sa makasaysayan nga datos sang sensor",
    "More closed-month history is needed before forecasting" to "Kinahanglan pa sang kasaysayan sang mga natapos nga bulan antes magtagna",
    "Monthly recommendation history" to "Kasaysayan sang binulan nga rekomendasyon",
    "Forecast results" to "Mga resulta sang tagna",
    "Why this crop" to "Ngaa ini nga tanom",
    "Best matching fields" to "Pinakamaayo nga nagakaangay nga mga field",
    "Fields to monitor" to "Mga field nga bantayan",
    "Used" to "Gin-gamit ang",
    "latest-month readings" to "mga pagbasa sang pinakabag-o nga bulan",
    "NPK and moisture ranges are provisional until locally calibrated" to "Pansamantala pa ang range sang NPK kag kaumog tubtob ma-calibrate sa lokal",
    "Forecast" to "Tagna",
    "Observed" to "Naobserbahan",
    "Observed month" to "Naobserbahan nga bulan",
    "Forecast matched" to "Nag-angay ang tagna",
    "Forecast differed" to "Nagkalain ang tagna",
    "High confidence" to "Mataas nga kumpiyansa",
    "Moderate confidence" to "Kasagarang kumpiyansa",
    "Low confidence" to "Manubo nga kumpiyansa",
    "Limited history" to "Limitado nga kasaysayan",
    "Decision support only: confirm the result with local weather, field conditions, and farming advice before planting" to "Giya lamang ini sa pagdesisyon: kumpirmaha anay sa lokal nga panahon, kondisyon sang latagon, kag laygay sa pagpanguma antes magtanom",
    "Second choice" to "Ikaduha nga pilian",
    "Reading stability" to "Katatagan sang mga pagbasa",
    "Stable readings" to "Matatag nga mga pagbasa",
    "Some variability" to "May pila ka pagbag-o",
    "High variability" to "Daku nga pagbag-o",
    "Unknown stability" to "Wala nahibaluan ang katatagan",
    "Variable fields" to "Mga field nga nagabag-o",
    "Measured ranges" to "Nasukod nga mga range",
    "Change from previous month" to "Pagbag-o halin sa nagligad nga bulan",
    "General Philippine wet season" to "Kasagarang tig-ululan sa Pilipinas",
    "General Philippine dry season" to "Kasagarang tig-ilinit sa Pilipinas",
    "Rainfall is often higher from May to October; confirm drainage and check a local forecast." to "Kasagarang mas madamo ang ulan halin Mayo tubtob Oktubre; kumpirmaha ang drainage kag tan-awa ang lokal nga tagna sang panahon.",
    "Rainfall is often lower from November to April; confirm irrigation and check a local forecast." to "Kasagarang mas diutay ang ulan halin Nobyembre tubtob Abril; kumpirmaha ang irigasyon kag tan-awa ang lokal nga tagna sang panahon.",
    "local farm outcomes considered" to "lokal nga resulta sang uma ang ginkonsiderar",
    "Sensor" to "Sensor",
    "Smart Farming Assistant" to "Maalam nga Manugbulig sa Pagpanguma",
    "Demo" to "Demo",
    "Settings" to "Mga Setting",
    "Back" to "Balik",
    "Farm & Device" to "Uma kag Device",
    "Farm or field name" to "Ngalan sang uma ukon latagon",
    "ESP32 device name" to "Ngalan sang ESP32 device",
    "Connection status" to "Kahimtangan sang koneksyon",
    "Online" to "Online",
    "Demo mode" to "Demo mode",
    "Offline" to "Offline",
    "Last synchronization" to "Katapusan nga pag-sync",
    "Waiting for data" to "Nagahulat sang datos",
    "Test connection" to "Tilawi ang koneksyon",
    "Restart ESP32" to "Sugdi liwat ang ESP32",
    "Alerts & Notifications" to "Mga Alerto kag Pahibalo",
    "All farm alerts" to "Tanan nga alerto sa uma",
    "Master control for sensor alerts" to "Panguna nga kontrol sang mga alerto sang sensor",
    "Low soil moisture" to "Manubo nga kaumog sang duta",
    "Warn when moisture is below the threshold" to "Magpahibalo kon manubo sa limitasyon ang kaumog",
    "Soil moisture threshold" to "Limitasyon sang kaumog sang duta",
    "High temperature" to "Mataas nga temperatura",
    "Minimum soil pH" to "Pinakanubo nga pH sang duta",
    "Maximum soil pH" to "Pinakamataas nga pH sang duta",
    "Device offline" to "Device nga offline",
    "Repeat alerts" to "Liwata ang mga alerto",
    "minutes" to "minutos",
    "Every" to "Kada",
    "Sound" to "Tingog",
    "Play a sound for important farm alerts" to "Magpatukar sang tingog para sa importante nga alerto sa uma",
    "Vibration" to "Pag-uyog",
    "Vibrate for important farm alerts" to "Mag-uyog para sa importante nga alerto sa uma",
    "Open Android notification settings" to "Abrihi ang notification settings sang Android",
    "Crop Profile" to "Profile sang Tanom",
    "Current crop" to "Karon nga tanom",
    "Crop variety" to "Sahi sang tanom",
    "Planting date" to "Petsa sang pagtanom",
    "Planting date (YYYY-MM-DD)" to "Petsa sang pagtanom (YYYY-MM-DD)",
    "Not set" to "Wala pa ginbutang",
    "Language & Offline Data" to "Lengguwahe kag Offline nga Datos",
    "Language" to "Lengguwahe",
    "Dark mode" to "Madulom nga mode",
    "Use a darker theme throughout the app" to "Gamita ang madulom nga tema sa bug-os nga app",
    "Offline data availability" to "Pagkaanaa sang offline nga datos",
    "Enabled · Firebase disk cache" to "Aktibo · Firebase disk cache",
    "Cloud history" to "Kasaysayan sa cloud",
    "Keep sensor history synchronized" to "Tipigi nga naka-sync ang kasaysayan sang sensor",
    "Account & Privacy" to "Account kag Pribasidad",
    "Farmer or administrator" to "Mangunguma ukon administrador",
    "Display name" to "Ngalan nga ipakita",
    "Role" to "Papel",
    "Farmer" to "Mangunguma",
    "Administrator" to "Administrador",
    "Sign-in status" to "Kahimtangan sang pag-sign in",
    "Guest / anonymous" to "Bisita / wala nakilala",
    "Change password" to "Ilisi ang password",
    "New password" to "Bag-o nga password",
    "Share diagnostic information" to "Ipaambit ang diagnostic information",
    "Helps troubleshoot sensor connection issues" to "Nagabulig sa pagpangita sang problema sa koneksyon sang sensor",
    "Sign out" to "Mag-sign out",
    "Save" to "Tipigi",
    "Cancel" to "Kanselahon",
    "Change" to "Ilisi",
    "Grow period" to "Panahon sang pagtubo",
    "days" to "mga adlaw",
    "Suitability" to "Pagkaangay",
    "Sensor Status" to "Kahimtangan sang Sensor",
    "Current Conditions" to "Karon nga Kahimtangan",
    "Monthly Sensor Collection" to "Binulan nga Pagtipon sang Datos sang Sensor",
    "Monthly Sensor Readings" to "Binulan nga mga Pagbasa sang Sensor",
    "Current month" to "Karon nga bulan",
    "readings" to "mga pagbasa",
    "Waiting for this month's sensor samples" to "Nagahulat sang mga pagbasa sang sensor sini nga bulan",
    "Waiting for monthly sensor samples" to "Nagahulat sang binulan nga mga pagbasa sang sensor",
    "Monthly averages" to "Binulan nga mga average",
    "Crop recommendations use these monthly averages" to "Ginagamit ang sini nga binulan nga mga average sa pagrekomendar sang tanom",
    "Based on" to "Base sa",
    "sensor readings collected this month" to "mga pagbasa sang sensor nga natipon sini nga bulan",
    "sensor readings from the latest available month" to "mga pagbasa sang sensor halin sa pinakabag-o nga bulan nga may datos",
    "A recommendation will appear after monthly sensor data is collected" to "Magaguwa ang rekomendasyon pagkatapos matipon ang binulan nga datos sang sensor",
    "Soil Moisture" to "Kaumog sang Duta",
    "Temperature" to "Temperatura",
    "Humidity" to "Kaumog sang Hangin",
    "Soil pH" to "pH sang Duta",
    "Nitrogen" to "Nitrogen",
    "Phosphorus" to "Phosphorus",
    "Potassium" to "Potassium",
    "Light Intensity" to "Kusog sang Kahayag",
    "Last sync" to "Katapusan nga sync",
    "waiting" to "nagahulat",
    "Settings saved in demo mode" to "Natipigan ang mga setting sa demo mode",
    "Settings synchronized" to "Na-sync ang mga setting",
    "Could not save settings" to "Indi matipigan ang mga setting"
)

fun localize(english: String, language: String): String =
    if (language.equals("Hiligaynon", ignoreCase = true)) hiligaynon[english] ?: english else english

@Composable
fun tr(english: String): String = localize(english, LocalCropCastLanguage.current)
